/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppStoreVersionBuildLinkageRequest struct for AppStoreVersionBuildLinkageRequest
type AppStoreVersionBuildLinkageRequest struct {
	Data AppStoreVersionRelationshipsBuildData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AppStoreVersionBuildLinkageRequest AppStoreVersionBuildLinkageRequest

// NewAppStoreVersionBuildLinkageRequest instantiates a new AppStoreVersionBuildLinkageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStoreVersionBuildLinkageRequest(data AppStoreVersionRelationshipsBuildData, ) *AppStoreVersionBuildLinkageRequest {
	this := AppStoreVersionBuildLinkageRequest{}
	this.Data = data
	return &this
}

// NewAppStoreVersionBuildLinkageRequestWithDefaults instantiates a new AppStoreVersionBuildLinkageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStoreVersionBuildLinkageRequestWithDefaults() *AppStoreVersionBuildLinkageRequest {
	this := AppStoreVersionBuildLinkageRequest{}
	return &this
}

// GetData returns the Data field value
func (o *AppStoreVersionBuildLinkageRequest) GetData() AppStoreVersionRelationshipsBuildData {
	if o == nil  {
		var ret AppStoreVersionRelationshipsBuildData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppStoreVersionBuildLinkageRequest) GetDataOk() (*AppStoreVersionRelationshipsBuildData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppStoreVersionBuildLinkageRequest) SetData(v AppStoreVersionRelationshipsBuildData) {
	o.Data = v
}

func (o AppStoreVersionBuildLinkageRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppStoreVersionBuildLinkageRequest) UnmarshalJSON(bytes []byte) (err error) {
	varAppStoreVersionBuildLinkageRequest := _AppStoreVersionBuildLinkageRequest{}

	if err = json.Unmarshal(bytes, &varAppStoreVersionBuildLinkageRequest); err == nil {
		*o = AppStoreVersionBuildLinkageRequest(varAppStoreVersionBuildLinkageRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppStoreVersionBuildLinkageRequest struct {
	value *AppStoreVersionBuildLinkageRequest
	isSet bool
}

func (v NullableAppStoreVersionBuildLinkageRequest) Get() *AppStoreVersionBuildLinkageRequest {
	return v.value
}

func (v *NullableAppStoreVersionBuildLinkageRequest) Set(val *AppStoreVersionBuildLinkageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStoreVersionBuildLinkageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStoreVersionBuildLinkageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStoreVersionBuildLinkageRequest(val *AppStoreVersionBuildLinkageRequest) *NullableAppStoreVersionBuildLinkageRequest {
	return &NullableAppStoreVersionBuildLinkageRequest{value: val, isSet: true}
}

func (v NullableAppStoreVersionBuildLinkageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStoreVersionBuildLinkageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


