/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BetaGroupRelationships struct for BetaGroupRelationships
type BetaGroupRelationships struct {
	App *AppEncryptionDeclarationRelationshipsApp `json:"app,omitempty"`
	Builds *AppRelationshipsBuilds `json:"builds,omitempty"`
	BetaTesters *BetaGroupRelationshipsBetaTesters `json:"betaTesters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BetaGroupRelationships BetaGroupRelationships

// NewBetaGroupRelationships instantiates a new BetaGroupRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaGroupRelationships() *BetaGroupRelationships {
	this := BetaGroupRelationships{}
	return &this
}

// NewBetaGroupRelationshipsWithDefaults instantiates a new BetaGroupRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaGroupRelationshipsWithDefaults() *BetaGroupRelationships {
	this := BetaGroupRelationships{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *BetaGroupRelationships) GetApp() AppEncryptionDeclarationRelationshipsApp {
	if o == nil || o.App == nil {
		var ret AppEncryptionDeclarationRelationshipsApp
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaGroupRelationships) GetAppOk() (*AppEncryptionDeclarationRelationshipsApp, bool) {
	if o == nil || o.App == nil {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *BetaGroupRelationships) HasApp() bool {
	if o != nil && o.App != nil {
		return true
	}

	return false
}

// SetApp gets a reference to the given AppEncryptionDeclarationRelationshipsApp and assigns it to the App field.
func (o *BetaGroupRelationships) SetApp(v AppEncryptionDeclarationRelationshipsApp) {
	o.App = &v
}

// GetBuilds returns the Builds field value if set, zero value otherwise.
func (o *BetaGroupRelationships) GetBuilds() AppRelationshipsBuilds {
	if o == nil || o.Builds == nil {
		var ret AppRelationshipsBuilds
		return ret
	}
	return *o.Builds
}

// GetBuildsOk returns a tuple with the Builds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaGroupRelationships) GetBuildsOk() (*AppRelationshipsBuilds, bool) {
	if o == nil || o.Builds == nil {
		return nil, false
	}
	return o.Builds, true
}

// HasBuilds returns a boolean if a field has been set.
func (o *BetaGroupRelationships) HasBuilds() bool {
	if o != nil && o.Builds != nil {
		return true
	}

	return false
}

// SetBuilds gets a reference to the given AppRelationshipsBuilds and assigns it to the Builds field.
func (o *BetaGroupRelationships) SetBuilds(v AppRelationshipsBuilds) {
	o.Builds = &v
}

// GetBetaTesters returns the BetaTesters field value if set, zero value otherwise.
func (o *BetaGroupRelationships) GetBetaTesters() BetaGroupRelationshipsBetaTesters {
	if o == nil || o.BetaTesters == nil {
		var ret BetaGroupRelationshipsBetaTesters
		return ret
	}
	return *o.BetaTesters
}

// GetBetaTestersOk returns a tuple with the BetaTesters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaGroupRelationships) GetBetaTestersOk() (*BetaGroupRelationshipsBetaTesters, bool) {
	if o == nil || o.BetaTesters == nil {
		return nil, false
	}
	return o.BetaTesters, true
}

// HasBetaTesters returns a boolean if a field has been set.
func (o *BetaGroupRelationships) HasBetaTesters() bool {
	if o != nil && o.BetaTesters != nil {
		return true
	}

	return false
}

// SetBetaTesters gets a reference to the given BetaGroupRelationshipsBetaTesters and assigns it to the BetaTesters field.
func (o *BetaGroupRelationships) SetBetaTesters(v BetaGroupRelationshipsBetaTesters) {
	o.BetaTesters = &v
}

func (o BetaGroupRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.App != nil {
		toSerialize["app"] = o.App
	}
	if o.Builds != nil {
		toSerialize["builds"] = o.Builds
	}
	if o.BetaTesters != nil {
		toSerialize["betaTesters"] = o.BetaTesters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BetaGroupRelationships) UnmarshalJSON(bytes []byte) (err error) {
	varBetaGroupRelationships := _BetaGroupRelationships{}

	if err = json.Unmarshal(bytes, &varBetaGroupRelationships); err == nil {
		*o = BetaGroupRelationships(varBetaGroupRelationships)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		delete(additionalProperties, "builds")
		delete(additionalProperties, "betaTesters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBetaGroupRelationships struct {
	value *BetaGroupRelationships
	isSet bool
}

func (v NullableBetaGroupRelationships) Get() *BetaGroupRelationships {
	return v.value
}

func (v *NullableBetaGroupRelationships) Set(val *BetaGroupRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaGroupRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaGroupRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaGroupRelationships(val *BetaGroupRelationships) *NullableBetaGroupRelationships {
	return &NullableBetaGroupRelationships{value: val, isSet: true}
}

func (v NullableBetaGroupRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaGroupRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


