/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreviewCreateRequestDataRelationships struct for AppPreviewCreateRequestDataRelationships
type AppPreviewCreateRequestDataRelationships struct {
	AppPreviewSet AppPreviewCreateRequestDataRelationshipsAppPreviewSet `json:"appPreviewSet"`
	AdditionalProperties map[string]interface{}
}

type _AppPreviewCreateRequestDataRelationships AppPreviewCreateRequestDataRelationships

// NewAppPreviewCreateRequestDataRelationships instantiates a new AppPreviewCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreviewCreateRequestDataRelationships(appPreviewSet AppPreviewCreateRequestDataRelationshipsAppPreviewSet, ) *AppPreviewCreateRequestDataRelationships {
	this := AppPreviewCreateRequestDataRelationships{}
	this.AppPreviewSet = appPreviewSet
	return &this
}

// NewAppPreviewCreateRequestDataRelationshipsWithDefaults instantiates a new AppPreviewCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreviewCreateRequestDataRelationshipsWithDefaults() *AppPreviewCreateRequestDataRelationships {
	this := AppPreviewCreateRequestDataRelationships{}
	return &this
}

// GetAppPreviewSet returns the AppPreviewSet field value
func (o *AppPreviewCreateRequestDataRelationships) GetAppPreviewSet() AppPreviewCreateRequestDataRelationshipsAppPreviewSet {
	if o == nil  {
		var ret AppPreviewCreateRequestDataRelationshipsAppPreviewSet
		return ret
	}

	return o.AppPreviewSet
}

// GetAppPreviewSetOk returns a tuple with the AppPreviewSet field value
// and a boolean to check if the value has been set.
func (o *AppPreviewCreateRequestDataRelationships) GetAppPreviewSetOk() (*AppPreviewCreateRequestDataRelationshipsAppPreviewSet, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AppPreviewSet, true
}

// SetAppPreviewSet sets field value
func (o *AppPreviewCreateRequestDataRelationships) SetAppPreviewSet(v AppPreviewCreateRequestDataRelationshipsAppPreviewSet) {
	o.AppPreviewSet = v
}

func (o AppPreviewCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["appPreviewSet"] = o.AppPreviewSet
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreviewCreateRequestDataRelationships) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreviewCreateRequestDataRelationships := _AppPreviewCreateRequestDataRelationships{}

	if err = json.Unmarshal(bytes, &varAppPreviewCreateRequestDataRelationships); err == nil {
		*o = AppPreviewCreateRequestDataRelationships(varAppPreviewCreateRequestDataRelationships)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appPreviewSet")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreviewCreateRequestDataRelationships struct {
	value *AppPreviewCreateRequestDataRelationships
	isSet bool
}

func (v NullableAppPreviewCreateRequestDataRelationships) Get() *AppPreviewCreateRequestDataRelationships {
	return v.value
}

func (v *NullableAppPreviewCreateRequestDataRelationships) Set(val *AppPreviewCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreviewCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreviewCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreviewCreateRequestDataRelationships(val *AppPreviewCreateRequestDataRelationships) *NullableAppPreviewCreateRequestDataRelationships {
	return &NullableAppPreviewCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableAppPreviewCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreviewCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


