/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppStoreReviewAttachmentUpdateRequest struct for AppStoreReviewAttachmentUpdateRequest
type AppStoreReviewAttachmentUpdateRequest struct {
	Data AppStoreReviewAttachmentUpdateRequestData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AppStoreReviewAttachmentUpdateRequest AppStoreReviewAttachmentUpdateRequest

// NewAppStoreReviewAttachmentUpdateRequest instantiates a new AppStoreReviewAttachmentUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStoreReviewAttachmentUpdateRequest(data AppStoreReviewAttachmentUpdateRequestData, ) *AppStoreReviewAttachmentUpdateRequest {
	this := AppStoreReviewAttachmentUpdateRequest{}
	this.Data = data
	return &this
}

// NewAppStoreReviewAttachmentUpdateRequestWithDefaults instantiates a new AppStoreReviewAttachmentUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStoreReviewAttachmentUpdateRequestWithDefaults() *AppStoreReviewAttachmentUpdateRequest {
	this := AppStoreReviewAttachmentUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *AppStoreReviewAttachmentUpdateRequest) GetData() AppStoreReviewAttachmentUpdateRequestData {
	if o == nil  {
		var ret AppStoreReviewAttachmentUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppStoreReviewAttachmentUpdateRequest) GetDataOk() (*AppStoreReviewAttachmentUpdateRequestData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppStoreReviewAttachmentUpdateRequest) SetData(v AppStoreReviewAttachmentUpdateRequestData) {
	o.Data = v
}

func (o AppStoreReviewAttachmentUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppStoreReviewAttachmentUpdateRequest) UnmarshalJSON(bytes []byte) (err error) {
	varAppStoreReviewAttachmentUpdateRequest := _AppStoreReviewAttachmentUpdateRequest{}

	if err = json.Unmarshal(bytes, &varAppStoreReviewAttachmentUpdateRequest); err == nil {
		*o = AppStoreReviewAttachmentUpdateRequest(varAppStoreReviewAttachmentUpdateRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppStoreReviewAttachmentUpdateRequest struct {
	value *AppStoreReviewAttachmentUpdateRequest
	isSet bool
}

func (v NullableAppStoreReviewAttachmentUpdateRequest) Get() *AppStoreReviewAttachmentUpdateRequest {
	return v.value
}

func (v *NullableAppStoreReviewAttachmentUpdateRequest) Set(val *AppStoreReviewAttachmentUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStoreReviewAttachmentUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStoreReviewAttachmentUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStoreReviewAttachmentUpdateRequest(val *AppStoreReviewAttachmentUpdateRequest) *NullableAppStoreReviewAttachmentUpdateRequest {
	return &NullableAppStoreReviewAttachmentUpdateRequest{value: val, isSet: true}
}

func (v NullableAppStoreReviewAttachmentUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStoreReviewAttachmentUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


