/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreOrderCreateRequestDataAttributes struct for AppPreOrderCreateRequestDataAttributes
type AppPreOrderCreateRequestDataAttributes struct {
	AppReleaseDate *string `json:"appReleaseDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AppPreOrderCreateRequestDataAttributes AppPreOrderCreateRequestDataAttributes

// NewAppPreOrderCreateRequestDataAttributes instantiates a new AppPreOrderCreateRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreOrderCreateRequestDataAttributes() *AppPreOrderCreateRequestDataAttributes {
	this := AppPreOrderCreateRequestDataAttributes{}
	return &this
}

// NewAppPreOrderCreateRequestDataAttributesWithDefaults instantiates a new AppPreOrderCreateRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreOrderCreateRequestDataAttributesWithDefaults() *AppPreOrderCreateRequestDataAttributes {
	this := AppPreOrderCreateRequestDataAttributes{}
	return &this
}

// GetAppReleaseDate returns the AppReleaseDate field value if set, zero value otherwise.
func (o *AppPreOrderCreateRequestDataAttributes) GetAppReleaseDate() string {
	if o == nil || o.AppReleaseDate == nil {
		var ret string
		return ret
	}
	return *o.AppReleaseDate
}

// GetAppReleaseDateOk returns a tuple with the AppReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppPreOrderCreateRequestDataAttributes) GetAppReleaseDateOk() (*string, bool) {
	if o == nil || o.AppReleaseDate == nil {
		return nil, false
	}
	return o.AppReleaseDate, true
}

// HasAppReleaseDate returns a boolean if a field has been set.
func (o *AppPreOrderCreateRequestDataAttributes) HasAppReleaseDate() bool {
	if o != nil && o.AppReleaseDate != nil {
		return true
	}

	return false
}

// SetAppReleaseDate gets a reference to the given string and assigns it to the AppReleaseDate field.
func (o *AppPreOrderCreateRequestDataAttributes) SetAppReleaseDate(v string) {
	o.AppReleaseDate = &v
}

func (o AppPreOrderCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AppReleaseDate != nil {
		toSerialize["appReleaseDate"] = o.AppReleaseDate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreOrderCreateRequestDataAttributes) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreOrderCreateRequestDataAttributes := _AppPreOrderCreateRequestDataAttributes{}

	if err = json.Unmarshal(bytes, &varAppPreOrderCreateRequestDataAttributes); err == nil {
		*o = AppPreOrderCreateRequestDataAttributes(varAppPreOrderCreateRequestDataAttributes)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appReleaseDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreOrderCreateRequestDataAttributes struct {
	value *AppPreOrderCreateRequestDataAttributes
	isSet bool
}

func (v NullableAppPreOrderCreateRequestDataAttributes) Get() *AppPreOrderCreateRequestDataAttributes {
	return v.value
}

func (v *NullableAppPreOrderCreateRequestDataAttributes) Set(val *AppPreOrderCreateRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreOrderCreateRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreOrderCreateRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreOrderCreateRequestDataAttributes(val *AppPreOrderCreateRequestDataAttributes) *NullableAppPreOrderCreateRequestDataAttributes {
	return &NullableAppPreOrderCreateRequestDataAttributes{value: val, isSet: true}
}

func (v NullableAppPreOrderCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreOrderCreateRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


