/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration struct for BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration
type BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration struct {
	Data *BuildRelationshipsAppEncryptionDeclarationData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration

// NewBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration instantiates a new BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration() *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration {
	this := BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration{}
	return &this
}

// NewBuildUpdateRequestDataRelationshipsAppEncryptionDeclarationWithDefaults instantiates a new BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildUpdateRequestDataRelationshipsAppEncryptionDeclarationWithDefaults() *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration {
	this := BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) GetData() BuildRelationshipsAppEncryptionDeclarationData {
	if o == nil || o.Data == nil {
		var ret BuildRelationshipsAppEncryptionDeclarationData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) GetDataOk() (*BuildRelationshipsAppEncryptionDeclarationData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given BuildRelationshipsAppEncryptionDeclarationData and assigns it to the Data field.
func (o *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) SetData(v BuildRelationshipsAppEncryptionDeclarationData) {
	o.Data = &v
}

func (o BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) UnmarshalJSON(bytes []byte) (err error) {
	varBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration := _BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration{}

	if err = json.Unmarshal(bytes, &varBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration); err == nil {
		*o = BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration(varBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration struct {
	value *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration
	isSet bool
}

func (v NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) Get() *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration {
	return v.value
}

func (v *NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) Set(val *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration(val *BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) *NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration {
	return &NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration{value: val, isSet: true}
}

func (v NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildUpdateRequestDataRelationshipsAppEncryptionDeclaration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


