/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreOrderCreateRequestDataRelationshipsApp struct for AppPreOrderCreateRequestDataRelationshipsApp
type AppPreOrderCreateRequestDataRelationshipsApp struct {
	Data AppEncryptionDeclarationRelationshipsAppData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AppPreOrderCreateRequestDataRelationshipsApp AppPreOrderCreateRequestDataRelationshipsApp

// NewAppPreOrderCreateRequestDataRelationshipsApp instantiates a new AppPreOrderCreateRequestDataRelationshipsApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreOrderCreateRequestDataRelationshipsApp(data AppEncryptionDeclarationRelationshipsAppData, ) *AppPreOrderCreateRequestDataRelationshipsApp {
	this := AppPreOrderCreateRequestDataRelationshipsApp{}
	this.Data = data
	return &this
}

// NewAppPreOrderCreateRequestDataRelationshipsAppWithDefaults instantiates a new AppPreOrderCreateRequestDataRelationshipsApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreOrderCreateRequestDataRelationshipsAppWithDefaults() *AppPreOrderCreateRequestDataRelationshipsApp {
	this := AppPreOrderCreateRequestDataRelationshipsApp{}
	return &this
}

// GetData returns the Data field value
func (o *AppPreOrderCreateRequestDataRelationshipsApp) GetData() AppEncryptionDeclarationRelationshipsAppData {
	if o == nil  {
		var ret AppEncryptionDeclarationRelationshipsAppData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppPreOrderCreateRequestDataRelationshipsApp) GetDataOk() (*AppEncryptionDeclarationRelationshipsAppData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppPreOrderCreateRequestDataRelationshipsApp) SetData(v AppEncryptionDeclarationRelationshipsAppData) {
	o.Data = v
}

func (o AppPreOrderCreateRequestDataRelationshipsApp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreOrderCreateRequestDataRelationshipsApp) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreOrderCreateRequestDataRelationshipsApp := _AppPreOrderCreateRequestDataRelationshipsApp{}

	if err = json.Unmarshal(bytes, &varAppPreOrderCreateRequestDataRelationshipsApp); err == nil {
		*o = AppPreOrderCreateRequestDataRelationshipsApp(varAppPreOrderCreateRequestDataRelationshipsApp)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreOrderCreateRequestDataRelationshipsApp struct {
	value *AppPreOrderCreateRequestDataRelationshipsApp
	isSet bool
}

func (v NullableAppPreOrderCreateRequestDataRelationshipsApp) Get() *AppPreOrderCreateRequestDataRelationshipsApp {
	return v.value
}

func (v *NullableAppPreOrderCreateRequestDataRelationshipsApp) Set(val *AppPreOrderCreateRequestDataRelationshipsApp) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreOrderCreateRequestDataRelationshipsApp) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreOrderCreateRequestDataRelationshipsApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreOrderCreateRequestDataRelationshipsApp(val *AppPreOrderCreateRequestDataRelationshipsApp) *NullableAppPreOrderCreateRequestDataRelationshipsApp {
	return &NullableAppPreOrderCreateRequestDataRelationshipsApp{value: val, isSet: true}
}

func (v NullableAppPreOrderCreateRequestDataRelationshipsApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreOrderCreateRequestDataRelationshipsApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


