/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BetaTesterResponse struct for BetaTesterResponse
type BetaTesterResponse struct {
	Data BetaTester `json:"data"`
	Included *[]OneOfAppBetaGroupBuild `json:"included,omitempty"`
	Links DocumentLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _BetaTesterResponse BetaTesterResponse

// NewBetaTesterResponse instantiates a new BetaTesterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaTesterResponse(data BetaTester, links DocumentLinks, ) *BetaTesterResponse {
	this := BetaTesterResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewBetaTesterResponseWithDefaults instantiates a new BetaTesterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaTesterResponseWithDefaults() *BetaTesterResponse {
	this := BetaTesterResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BetaTesterResponse) GetData() BetaTester {
	if o == nil  {
		var ret BetaTester
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BetaTesterResponse) GetDataOk() (*BetaTester, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BetaTesterResponse) SetData(v BetaTester) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *BetaTesterResponse) GetIncluded() []OneOfAppBetaGroupBuild {
	if o == nil || o.Included == nil {
		var ret []OneOfAppBetaGroupBuild
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaTesterResponse) GetIncludedOk() (*[]OneOfAppBetaGroupBuild, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *BetaTesterResponse) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []OneOfAppBetaGroupBuild and assigns it to the Included field.
func (o *BetaTesterResponse) SetIncluded(v []OneOfAppBetaGroupBuild) {
	o.Included = &v
}

// GetLinks returns the Links field value
func (o *BetaTesterResponse) GetLinks() DocumentLinks {
	if o == nil  {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BetaTesterResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BetaTesterResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o BetaTesterResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	if true {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BetaTesterResponse) UnmarshalJSON(bytes []byte) (err error) {
	varBetaTesterResponse := _BetaTesterResponse{}

	if err = json.Unmarshal(bytes, &varBetaTesterResponse); err == nil {
		*o = BetaTesterResponse(varBetaTesterResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "included")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBetaTesterResponse struct {
	value *BetaTesterResponse
	isSet bool
}

func (v NullableBetaTesterResponse) Get() *BetaTesterResponse {
	return v.value
}

func (v *NullableBetaTesterResponse) Set(val *BetaTesterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaTesterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaTesterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaTesterResponse(val *BetaTesterResponse) *NullableBetaTesterResponse {
	return &NullableBetaTesterResponse{value: val, isSet: true}
}

func (v NullableBetaTesterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaTesterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


