/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// DiagnosticSignaturesResponse struct for DiagnosticSignaturesResponse
type DiagnosticSignaturesResponse struct {
	Data []DiagnosticSignature `json:"data"`
	Included *[]DiagnosticLog `json:"included,omitempty"`
	Links PagedDocumentLinks `json:"links"`
	Meta *PagingInformation `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DiagnosticSignaturesResponse DiagnosticSignaturesResponse

// NewDiagnosticSignaturesResponse instantiates a new DiagnosticSignaturesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiagnosticSignaturesResponse(data []DiagnosticSignature, links PagedDocumentLinks, ) *DiagnosticSignaturesResponse {
	this := DiagnosticSignaturesResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewDiagnosticSignaturesResponseWithDefaults instantiates a new DiagnosticSignaturesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiagnosticSignaturesResponseWithDefaults() *DiagnosticSignaturesResponse {
	this := DiagnosticSignaturesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DiagnosticSignaturesResponse) GetData() []DiagnosticSignature {
	if o == nil  {
		var ret []DiagnosticSignature
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DiagnosticSignaturesResponse) GetDataOk() (*[]DiagnosticSignature, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DiagnosticSignaturesResponse) SetData(v []DiagnosticSignature) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *DiagnosticSignaturesResponse) GetIncluded() []DiagnosticLog {
	if o == nil || o.Included == nil {
		var ret []DiagnosticLog
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticSignaturesResponse) GetIncludedOk() (*[]DiagnosticLog, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *DiagnosticSignaturesResponse) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []DiagnosticLog and assigns it to the Included field.
func (o *DiagnosticSignaturesResponse) SetIncluded(v []DiagnosticLog) {
	o.Included = &v
}

// GetLinks returns the Links field value
func (o *DiagnosticSignaturesResponse) GetLinks() PagedDocumentLinks {
	if o == nil  {
		var ret PagedDocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *DiagnosticSignaturesResponse) GetLinksOk() (*PagedDocumentLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *DiagnosticSignaturesResponse) SetLinks(v PagedDocumentLinks) {
	o.Links = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *DiagnosticSignaturesResponse) GetMeta() PagingInformation {
	if o == nil || o.Meta == nil {
		var ret PagingInformation
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiagnosticSignaturesResponse) GetMetaOk() (*PagingInformation, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *DiagnosticSignaturesResponse) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PagingInformation and assigns it to the Meta field.
func (o *DiagnosticSignaturesResponse) SetMeta(v PagingInformation) {
	o.Meta = &v
}

func (o DiagnosticSignaturesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	if true {
		toSerialize["links"] = o.Links
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DiagnosticSignaturesResponse) UnmarshalJSON(bytes []byte) (err error) {
	varDiagnosticSignaturesResponse := _DiagnosticSignaturesResponse{}

	if err = json.Unmarshal(bytes, &varDiagnosticSignaturesResponse); err == nil {
		*o = DiagnosticSignaturesResponse(varDiagnosticSignaturesResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "included")
		delete(additionalProperties, "links")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDiagnosticSignaturesResponse struct {
	value *DiagnosticSignaturesResponse
	isSet bool
}

func (v NullableDiagnosticSignaturesResponse) Get() *DiagnosticSignaturesResponse {
	return v.value
}

func (v *NullableDiagnosticSignaturesResponse) Set(val *DiagnosticSignaturesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDiagnosticSignaturesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDiagnosticSignaturesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiagnosticSignaturesResponse(val *DiagnosticSignaturesResponse) *NullableDiagnosticSignaturesResponse {
	return &NullableDiagnosticSignaturesResponse{value: val, isSet: true}
}

func (v NullableDiagnosticSignaturesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiagnosticSignaturesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


