/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BuildBetaGroupsLinkagesRequest struct for BuildBetaGroupsLinkagesRequest
type BuildBetaGroupsLinkagesRequest struct {
	Data []AppRelationshipsBetaGroupsData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _BuildBetaGroupsLinkagesRequest BuildBetaGroupsLinkagesRequest

// NewBuildBetaGroupsLinkagesRequest instantiates a new BuildBetaGroupsLinkagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildBetaGroupsLinkagesRequest(data []AppRelationshipsBetaGroupsData, ) *BuildBetaGroupsLinkagesRequest {
	this := BuildBetaGroupsLinkagesRequest{}
	this.Data = data
	return &this
}

// NewBuildBetaGroupsLinkagesRequestWithDefaults instantiates a new BuildBetaGroupsLinkagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildBetaGroupsLinkagesRequestWithDefaults() *BuildBetaGroupsLinkagesRequest {
	this := BuildBetaGroupsLinkagesRequest{}
	return &this
}

// GetData returns the Data field value
func (o *BuildBetaGroupsLinkagesRequest) GetData() []AppRelationshipsBetaGroupsData {
	if o == nil  {
		var ret []AppRelationshipsBetaGroupsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BuildBetaGroupsLinkagesRequest) GetDataOk() (*[]AppRelationshipsBetaGroupsData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BuildBetaGroupsLinkagesRequest) SetData(v []AppRelationshipsBetaGroupsData) {
	o.Data = v
}

func (o BuildBetaGroupsLinkagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BuildBetaGroupsLinkagesRequest) UnmarshalJSON(bytes []byte) (err error) {
	varBuildBetaGroupsLinkagesRequest := _BuildBetaGroupsLinkagesRequest{}

	if err = json.Unmarshal(bytes, &varBuildBetaGroupsLinkagesRequest); err == nil {
		*o = BuildBetaGroupsLinkagesRequest(varBuildBetaGroupsLinkagesRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuildBetaGroupsLinkagesRequest struct {
	value *BuildBetaGroupsLinkagesRequest
	isSet bool
}

func (v NullableBuildBetaGroupsLinkagesRequest) Get() *BuildBetaGroupsLinkagesRequest {
	return v.value
}

func (v *NullableBuildBetaGroupsLinkagesRequest) Set(val *BuildBetaGroupsLinkagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildBetaGroupsLinkagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildBetaGroupsLinkagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildBetaGroupsLinkagesRequest(val *BuildBetaGroupsLinkagesRequest) *NullableBuildBetaGroupsLinkagesRequest {
	return &NullableBuildBetaGroupsLinkagesRequest{value: val, isSet: true}
}

func (v NullableBuildBetaGroupsLinkagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildBetaGroupsLinkagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


