/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppEncryptionDeclaration struct for AppEncryptionDeclaration
type AppEncryptionDeclaration struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Attributes *AppEncryptionDeclarationAttributes `json:"attributes,omitempty"`
	Relationships *AppEncryptionDeclarationRelationships `json:"relationships,omitempty"`
	Links ResourceLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _AppEncryptionDeclaration AppEncryptionDeclaration

// NewAppEncryptionDeclaration instantiates a new AppEncryptionDeclaration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppEncryptionDeclaration(type_ string, id string, links ResourceLinks, ) *AppEncryptionDeclaration {
	this := AppEncryptionDeclaration{}
	this.Type = type_
	this.Id = id
	this.Links = links
	return &this
}

// NewAppEncryptionDeclarationWithDefaults instantiates a new AppEncryptionDeclaration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppEncryptionDeclarationWithDefaults() *AppEncryptionDeclaration {
	this := AppEncryptionDeclaration{}
	return &this
}

// GetType returns the Type field value
func (o *AppEncryptionDeclaration) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclaration) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppEncryptionDeclaration) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *AppEncryptionDeclaration) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclaration) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppEncryptionDeclaration) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *AppEncryptionDeclaration) GetAttributes() AppEncryptionDeclarationAttributes {
	if o == nil || o.Attributes == nil {
		var ret AppEncryptionDeclarationAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclaration) GetAttributesOk() (*AppEncryptionDeclarationAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *AppEncryptionDeclaration) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given AppEncryptionDeclarationAttributes and assigns it to the Attributes field.
func (o *AppEncryptionDeclaration) SetAttributes(v AppEncryptionDeclarationAttributes) {
	o.Attributes = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *AppEncryptionDeclaration) GetRelationships() AppEncryptionDeclarationRelationships {
	if o == nil || o.Relationships == nil {
		var ret AppEncryptionDeclarationRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclaration) GetRelationshipsOk() (*AppEncryptionDeclarationRelationships, bool) {
	if o == nil || o.Relationships == nil {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *AppEncryptionDeclaration) HasRelationships() bool {
	if o != nil && o.Relationships != nil {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given AppEncryptionDeclarationRelationships and assigns it to the Relationships field.
func (o *AppEncryptionDeclaration) SetRelationships(v AppEncryptionDeclarationRelationships) {
	o.Relationships = &v
}

// GetLinks returns the Links field value
func (o *AppEncryptionDeclaration) GetLinks() ResourceLinks {
	if o == nil  {
		var ret ResourceLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclaration) GetLinksOk() (*ResourceLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AppEncryptionDeclaration) SetLinks(v ResourceLinks) {
	o.Links = v
}

func (o AppEncryptionDeclaration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	if true {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppEncryptionDeclaration) UnmarshalJSON(bytes []byte) (err error) {
	varAppEncryptionDeclaration := _AppEncryptionDeclaration{}

	if err = json.Unmarshal(bytes, &varAppEncryptionDeclaration); err == nil {
		*o = AppEncryptionDeclaration(varAppEncryptionDeclaration)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "relationships")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppEncryptionDeclaration struct {
	value *AppEncryptionDeclaration
	isSet bool
}

func (v NullableAppEncryptionDeclaration) Get() *AppEncryptionDeclaration {
	return v.value
}

func (v *NullableAppEncryptionDeclaration) Set(val *AppEncryptionDeclaration) {
	v.value = val
	v.isSet = true
}

func (v NullableAppEncryptionDeclaration) IsSet() bool {
	return v.isSet
}

func (v *NullableAppEncryptionDeclaration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppEncryptionDeclaration(val *AppEncryptionDeclaration) *NullableAppEncryptionDeclaration {
	return &NullableAppEncryptionDeclaration{value: val, isSet: true}
}

func (v NullableAppEncryptionDeclaration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppEncryptionDeclaration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


