/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreviewSetCreateRequestDataAttributes struct for AppPreviewSetCreateRequestDataAttributes
type AppPreviewSetCreateRequestDataAttributes struct {
	PreviewType PreviewType `json:"previewType"`
	AdditionalProperties map[string]interface{}
}

type _AppPreviewSetCreateRequestDataAttributes AppPreviewSetCreateRequestDataAttributes

// NewAppPreviewSetCreateRequestDataAttributes instantiates a new AppPreviewSetCreateRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreviewSetCreateRequestDataAttributes(previewType PreviewType, ) *AppPreviewSetCreateRequestDataAttributes {
	this := AppPreviewSetCreateRequestDataAttributes{}
	this.PreviewType = previewType
	return &this
}

// NewAppPreviewSetCreateRequestDataAttributesWithDefaults instantiates a new AppPreviewSetCreateRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreviewSetCreateRequestDataAttributesWithDefaults() *AppPreviewSetCreateRequestDataAttributes {
	this := AppPreviewSetCreateRequestDataAttributes{}
	return &this
}

// GetPreviewType returns the PreviewType field value
func (o *AppPreviewSetCreateRequestDataAttributes) GetPreviewType() PreviewType {
	if o == nil  {
		var ret PreviewType
		return ret
	}

	return o.PreviewType
}

// GetPreviewTypeOk returns a tuple with the PreviewType field value
// and a boolean to check if the value has been set.
func (o *AppPreviewSetCreateRequestDataAttributes) GetPreviewTypeOk() (*PreviewType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PreviewType, true
}

// SetPreviewType sets field value
func (o *AppPreviewSetCreateRequestDataAttributes) SetPreviewType(v PreviewType) {
	o.PreviewType = v
}

func (o AppPreviewSetCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["previewType"] = o.PreviewType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreviewSetCreateRequestDataAttributes) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreviewSetCreateRequestDataAttributes := _AppPreviewSetCreateRequestDataAttributes{}

	if err = json.Unmarshal(bytes, &varAppPreviewSetCreateRequestDataAttributes); err == nil {
		*o = AppPreviewSetCreateRequestDataAttributes(varAppPreviewSetCreateRequestDataAttributes)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "previewType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreviewSetCreateRequestDataAttributes struct {
	value *AppPreviewSetCreateRequestDataAttributes
	isSet bool
}

func (v NullableAppPreviewSetCreateRequestDataAttributes) Get() *AppPreviewSetCreateRequestDataAttributes {
	return v.value
}

func (v *NullableAppPreviewSetCreateRequestDataAttributes) Set(val *AppPreviewSetCreateRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreviewSetCreateRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreviewSetCreateRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreviewSetCreateRequestDataAttributes(val *AppPreviewSetCreateRequestDataAttributes) *NullableAppPreviewSetCreateRequestDataAttributes {
	return &NullableAppPreviewSetCreateRequestDataAttributes{value: val, isSet: true}
}

func (v NullableAppPreviewSetCreateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreviewSetCreateRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


