/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BuildRelationshipsIcons struct for BuildRelationshipsIcons
type BuildRelationshipsIcons struct {
	Links *AppCategoryRelationshipsSubcategoriesLinks `json:"links,omitempty"`
	Meta *PagingInformation `json:"meta,omitempty"`
	Data *[]BuildRelationshipsIconsData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BuildRelationshipsIcons BuildRelationshipsIcons

// NewBuildRelationshipsIcons instantiates a new BuildRelationshipsIcons object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildRelationshipsIcons() *BuildRelationshipsIcons {
	this := BuildRelationshipsIcons{}
	return &this
}

// NewBuildRelationshipsIconsWithDefaults instantiates a new BuildRelationshipsIcons object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildRelationshipsIconsWithDefaults() *BuildRelationshipsIcons {
	this := BuildRelationshipsIcons{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *BuildRelationshipsIcons) GetLinks() AppCategoryRelationshipsSubcategoriesLinks {
	if o == nil || o.Links == nil {
		var ret AppCategoryRelationshipsSubcategoriesLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildRelationshipsIcons) GetLinksOk() (*AppCategoryRelationshipsSubcategoriesLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *BuildRelationshipsIcons) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given AppCategoryRelationshipsSubcategoriesLinks and assigns it to the Links field.
func (o *BuildRelationshipsIcons) SetLinks(v AppCategoryRelationshipsSubcategoriesLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BuildRelationshipsIcons) GetMeta() PagingInformation {
	if o == nil || o.Meta == nil {
		var ret PagingInformation
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildRelationshipsIcons) GetMetaOk() (*PagingInformation, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BuildRelationshipsIcons) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PagingInformation and assigns it to the Meta field.
func (o *BuildRelationshipsIcons) SetMeta(v PagingInformation) {
	o.Meta = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BuildRelationshipsIcons) GetData() []BuildRelationshipsIconsData {
	if o == nil || o.Data == nil {
		var ret []BuildRelationshipsIconsData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildRelationshipsIcons) GetDataOk() (*[]BuildRelationshipsIconsData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BuildRelationshipsIcons) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []BuildRelationshipsIconsData and assigns it to the Data field.
func (o *BuildRelationshipsIcons) SetData(v []BuildRelationshipsIconsData) {
	o.Data = &v
}

func (o BuildRelationshipsIcons) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BuildRelationshipsIcons) UnmarshalJSON(bytes []byte) (err error) {
	varBuildRelationshipsIcons := _BuildRelationshipsIcons{}

	if err = json.Unmarshal(bytes, &varBuildRelationshipsIcons); err == nil {
		*o = BuildRelationshipsIcons(varBuildRelationshipsIcons)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "links")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuildRelationshipsIcons struct {
	value *BuildRelationshipsIcons
	isSet bool
}

func (v NullableBuildRelationshipsIcons) Get() *BuildRelationshipsIcons {
	return v.value
}

func (v *NullableBuildRelationshipsIcons) Set(val *BuildRelationshipsIcons) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildRelationshipsIcons) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildRelationshipsIcons) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildRelationshipsIcons(val *BuildRelationshipsIcons) *NullableBuildRelationshipsIcons {
	return &NullableBuildRelationshipsIcons{value: val, isSet: true}
}

func (v NullableBuildRelationshipsIcons) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildRelationshipsIcons) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


