/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild struct for BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild
type BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild struct {
	Data AppStoreVersionRelationshipsBuildData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild

// NewBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild instantiates a new BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild(data AppStoreVersionRelationshipsBuildData, ) *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
	this := BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild{}
	this.Data = data
	return &this
}

// NewBetaAppReviewSubmissionCreateRequestDataRelationshipsBuildWithDefaults instantiates a new BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaAppReviewSubmissionCreateRequestDataRelationshipsBuildWithDefaults() *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
	this := BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild{}
	return &this
}

// GetData returns the Data field value
func (o *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) GetData() AppStoreVersionRelationshipsBuildData {
	if o == nil  {
		var ret AppStoreVersionRelationshipsBuildData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) GetDataOk() (*AppStoreVersionRelationshipsBuildData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) SetData(v AppStoreVersionRelationshipsBuildData) {
	o.Data = v
}

func (o BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) UnmarshalJSON(bytes []byte) (err error) {
	varBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild := _BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild{}

	if err = json.Unmarshal(bytes, &varBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild); err == nil {
		*o = BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild(varBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild struct {
	value *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild
	isSet bool
}

func (v NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) Get() *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
	return v.value
}

func (v *NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) Set(val *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild(val *BetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) *NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild {
	return &NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild{value: val, isSet: true}
}

func (v NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaAppReviewSubmissionCreateRequestDataRelationshipsBuild) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


