/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreOrderCreateRequestDataRelationships struct for AppPreOrderCreateRequestDataRelationships
type AppPreOrderCreateRequestDataRelationships struct {
	App AppPreOrderCreateRequestDataRelationshipsApp `json:"app"`
	AdditionalProperties map[string]interface{}
}

type _AppPreOrderCreateRequestDataRelationships AppPreOrderCreateRequestDataRelationships

// NewAppPreOrderCreateRequestDataRelationships instantiates a new AppPreOrderCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreOrderCreateRequestDataRelationships(app AppPreOrderCreateRequestDataRelationshipsApp, ) *AppPreOrderCreateRequestDataRelationships {
	this := AppPreOrderCreateRequestDataRelationships{}
	this.App = app
	return &this
}

// NewAppPreOrderCreateRequestDataRelationshipsWithDefaults instantiates a new AppPreOrderCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreOrderCreateRequestDataRelationshipsWithDefaults() *AppPreOrderCreateRequestDataRelationships {
	this := AppPreOrderCreateRequestDataRelationships{}
	return &this
}

// GetApp returns the App field value
func (o *AppPreOrderCreateRequestDataRelationships) GetApp() AppPreOrderCreateRequestDataRelationshipsApp {
	if o == nil  {
		var ret AppPreOrderCreateRequestDataRelationshipsApp
		return ret
	}

	return o.App
}

// GetAppOk returns a tuple with the App field value
// and a boolean to check if the value has been set.
func (o *AppPreOrderCreateRequestDataRelationships) GetAppOk() (*AppPreOrderCreateRequestDataRelationshipsApp, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.App, true
}

// SetApp sets field value
func (o *AppPreOrderCreateRequestDataRelationships) SetApp(v AppPreOrderCreateRequestDataRelationshipsApp) {
	o.App = v
}

func (o AppPreOrderCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["app"] = o.App
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreOrderCreateRequestDataRelationships) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreOrderCreateRequestDataRelationships := _AppPreOrderCreateRequestDataRelationships{}

	if err = json.Unmarshal(bytes, &varAppPreOrderCreateRequestDataRelationships); err == nil {
		*o = AppPreOrderCreateRequestDataRelationships(varAppPreOrderCreateRequestDataRelationships)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreOrderCreateRequestDataRelationships struct {
	value *AppPreOrderCreateRequestDataRelationships
	isSet bool
}

func (v NullableAppPreOrderCreateRequestDataRelationships) Get() *AppPreOrderCreateRequestDataRelationships {
	return v.value
}

func (v *NullableAppPreOrderCreateRequestDataRelationships) Set(val *AppPreOrderCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreOrderCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreOrderCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreOrderCreateRequestDataRelationships(val *AppPreOrderCreateRequestDataRelationships) *NullableAppPreOrderCreateRequestDataRelationships {
	return &NullableAppPreOrderCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableAppPreOrderCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreOrderCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


