/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppPreviewUpdateRequest struct for AppPreviewUpdateRequest
type AppPreviewUpdateRequest struct {
	Data AppPreviewUpdateRequestData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AppPreviewUpdateRequest AppPreviewUpdateRequest

// NewAppPreviewUpdateRequest instantiates a new AppPreviewUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPreviewUpdateRequest(data AppPreviewUpdateRequestData, ) *AppPreviewUpdateRequest {
	this := AppPreviewUpdateRequest{}
	this.Data = data
	return &this
}

// NewAppPreviewUpdateRequestWithDefaults instantiates a new AppPreviewUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPreviewUpdateRequestWithDefaults() *AppPreviewUpdateRequest {
	this := AppPreviewUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *AppPreviewUpdateRequest) GetData() AppPreviewUpdateRequestData {
	if o == nil  {
		var ret AppPreviewUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppPreviewUpdateRequest) GetDataOk() (*AppPreviewUpdateRequestData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppPreviewUpdateRequest) SetData(v AppPreviewUpdateRequestData) {
	o.Data = v
}

func (o AppPreviewUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppPreviewUpdateRequest) UnmarshalJSON(bytes []byte) (err error) {
	varAppPreviewUpdateRequest := _AppPreviewUpdateRequest{}

	if err = json.Unmarshal(bytes, &varAppPreviewUpdateRequest); err == nil {
		*o = AppPreviewUpdateRequest(varAppPreviewUpdateRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppPreviewUpdateRequest struct {
	value *AppPreviewUpdateRequest
	isSet bool
}

func (v NullableAppPreviewUpdateRequest) Get() *AppPreviewUpdateRequest {
	return v.value
}

func (v *NullableAppPreviewUpdateRequest) Set(val *AppPreviewUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPreviewUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPreviewUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPreviewUpdateRequest(val *AppPreviewUpdateRequest) *NullableAppPreviewUpdateRequest {
	return &NullableAppPreviewUpdateRequest{value: val, isSet: true}
}

func (v NullableAppPreviewUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPreviewUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


