/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// BuildBetaNotification struct for BuildBetaNotification
type BuildBetaNotification struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Links ResourceLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _BuildBetaNotification BuildBetaNotification

// NewBuildBetaNotification instantiates a new BuildBetaNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildBetaNotification(type_ string, id string, links ResourceLinks, ) *BuildBetaNotification {
	this := BuildBetaNotification{}
	this.Type = type_
	this.Id = id
	this.Links = links
	return &this
}

// NewBuildBetaNotificationWithDefaults instantiates a new BuildBetaNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildBetaNotificationWithDefaults() *BuildBetaNotification {
	this := BuildBetaNotification{}
	return &this
}

// GetType returns the Type field value
func (o *BuildBetaNotification) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BuildBetaNotification) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BuildBetaNotification) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *BuildBetaNotification) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BuildBetaNotification) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BuildBetaNotification) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value
func (o *BuildBetaNotification) GetLinks() ResourceLinks {
	if o == nil  {
		var ret ResourceLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BuildBetaNotification) GetLinksOk() (*ResourceLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BuildBetaNotification) SetLinks(v ResourceLinks) {
	o.Links = v
}

func (o BuildBetaNotification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BuildBetaNotification) UnmarshalJSON(bytes []byte) (err error) {
	varBuildBetaNotification := _BuildBetaNotification{}

	if err = json.Unmarshal(bytes, &varBuildBetaNotification); err == nil {
		*o = BuildBetaNotification(varBuildBetaNotification)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuildBetaNotification struct {
	value *BuildBetaNotification
	isSet bool
}

func (v NullableBuildBetaNotification) Get() *BuildBetaNotification {
	return v.value
}

func (v *NullableBuildBetaNotification) Set(val *BuildBetaNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildBetaNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildBetaNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildBetaNotification(val *BuildBetaNotification) *NullableBuildBetaNotification {
	return &NullableBuildBetaNotification{value: val, isSet: true}
}

func (v NullableBuildBetaNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildBetaNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


