/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppInfoLocalizationResponse struct for AppInfoLocalizationResponse
type AppInfoLocalizationResponse struct {
	Data AppInfoLocalization `json:"data"`
	Links DocumentLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _AppInfoLocalizationResponse AppInfoLocalizationResponse

// NewAppInfoLocalizationResponse instantiates a new AppInfoLocalizationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInfoLocalizationResponse(data AppInfoLocalization, links DocumentLinks, ) *AppInfoLocalizationResponse {
	this := AppInfoLocalizationResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewAppInfoLocalizationResponseWithDefaults instantiates a new AppInfoLocalizationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInfoLocalizationResponseWithDefaults() *AppInfoLocalizationResponse {
	this := AppInfoLocalizationResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AppInfoLocalizationResponse) GetData() AppInfoLocalization {
	if o == nil  {
		var ret AppInfoLocalization
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppInfoLocalizationResponse) GetDataOk() (*AppInfoLocalization, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppInfoLocalizationResponse) SetData(v AppInfoLocalization) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *AppInfoLocalizationResponse) GetLinks() DocumentLinks {
	if o == nil  {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AppInfoLocalizationResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AppInfoLocalizationResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o AppInfoLocalizationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppInfoLocalizationResponse) UnmarshalJSON(bytes []byte) (err error) {
	varAppInfoLocalizationResponse := _AppInfoLocalizationResponse{}

	if err = json.Unmarshal(bytes, &varAppInfoLocalizationResponse); err == nil {
		*o = AppInfoLocalizationResponse(varAppInfoLocalizationResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppInfoLocalizationResponse struct {
	value *AppInfoLocalizationResponse
	isSet bool
}

func (v NullableAppInfoLocalizationResponse) Get() *AppInfoLocalizationResponse {
	return v.value
}

func (v *NullableAppInfoLocalizationResponse) Set(val *AppInfoLocalizationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInfoLocalizationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInfoLocalizationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInfoLocalizationResponse(val *AppInfoLocalizationResponse) *NullableAppInfoLocalizationResponse {
	return &NullableAppInfoLocalizationResponse{value: val, isSet: true}
}

func (v NullableAppInfoLocalizationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInfoLocalizationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


