/*
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// AppRelationshipsPreOrder struct for AppRelationshipsPreOrder
type AppRelationshipsPreOrder struct {
	Links *AppCategoryRelationshipsSubcategoriesLinks `json:"links,omitempty"`
	Data *AppRelationshipsPreOrderData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AppRelationshipsPreOrder AppRelationshipsPreOrder

// NewAppRelationshipsPreOrder instantiates a new AppRelationshipsPreOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppRelationshipsPreOrder() *AppRelationshipsPreOrder {
	this := AppRelationshipsPreOrder{}
	return &this
}

// NewAppRelationshipsPreOrderWithDefaults instantiates a new AppRelationshipsPreOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppRelationshipsPreOrderWithDefaults() *AppRelationshipsPreOrder {
	this := AppRelationshipsPreOrder{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AppRelationshipsPreOrder) GetLinks() AppCategoryRelationshipsSubcategoriesLinks {
	if o == nil || o.Links == nil {
		var ret AppCategoryRelationshipsSubcategoriesLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppRelationshipsPreOrder) GetLinksOk() (*AppCategoryRelationshipsSubcategoriesLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AppRelationshipsPreOrder) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given AppCategoryRelationshipsSubcategoriesLinks and assigns it to the Links field.
func (o *AppRelationshipsPreOrder) SetLinks(v AppCategoryRelationshipsSubcategoriesLinks) {
	o.Links = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AppRelationshipsPreOrder) GetData() AppRelationshipsPreOrderData {
	if o == nil || o.Data == nil {
		var ret AppRelationshipsPreOrderData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppRelationshipsPreOrder) GetDataOk() (*AppRelationshipsPreOrderData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AppRelationshipsPreOrder) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given AppRelationshipsPreOrderData and assigns it to the Data field.
func (o *AppRelationshipsPreOrder) SetData(v AppRelationshipsPreOrderData) {
	o.Data = &v
}

func (o AppRelationshipsPreOrder) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AppRelationshipsPreOrder) UnmarshalJSON(bytes []byte) (err error) {
	varAppRelationshipsPreOrder := _AppRelationshipsPreOrder{}

	if err = json.Unmarshal(bytes, &varAppRelationshipsPreOrder); err == nil {
		*o = AppRelationshipsPreOrder(varAppRelationshipsPreOrder)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "links")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppRelationshipsPreOrder struct {
	value *AppRelationshipsPreOrder
	isSet bool
}

func (v NullableAppRelationshipsPreOrder) Get() *AppRelationshipsPreOrder {
	return v.value
}

func (v *NullableAppRelationshipsPreOrder) Set(val *AppRelationshipsPreOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRelationshipsPreOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRelationshipsPreOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRelationshipsPreOrder(val *AppRelationshipsPreOrder) *NullableAppRelationshipsPreOrder {
	return &NullableAppRelationshipsPreOrder{value: val, isSet: true}
}

func (v NullableAppRelationshipsPreOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRelationshipsPreOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


